import {
  BusinessPreset,
  CartItem,
  MenuCategory,
  MenuItem,
  Order,
  StaffMember,
  TenantConfig,
  ThemeColors,
  ThemeName,
} from '../types';

export const THEMES: Record<ThemeName, ThemeColors> = {
  'Retail Aurora': {
    primary: '#1d4ed8',
    primaryHover: '#1e40af',
    accent: '#f97316',
    bg: '#eef4ff',
    surface: '#ffffff',
    border: '#d6e4ff',
    text: '#10203a',
    body: '#334155',
    muted: '#64748b',
  },
  'Cafe Cream': {
    primary: '#7c3a15',
    primaryHover: '#5b260d',
    accent: '#f59e0b',
    bg: '#fff8ef',
    surface: '#fffdf9',
    border: '#fde7c7',
    text: '#40210b',
    body: '#7c4a27',
    muted: '#b1743d',
  },
  'Studio Pop': {
    primary: '#db2777',
    primaryHover: '#be185d',
    accent: '#0ea5e9',
    bg: '#fff1f7',
    surface: '#ffffff',
    border: '#ffd4e7',
    text: '#4a1430',
    body: '#6b2146',
    muted: '#9d4d72',
  },
  'Green Grocer': {
    primary: '#0f766e',
    primaryHover: '#115e59',
    accent: '#f59e0b',
    bg: '#f2fbf7',
    surface: '#ffffff',
    border: '#d2f1df',
    text: '#08372f',
    body: '#24524a',
    muted: '#5f8a7d',
  },
  'Luxury Mono': {
    primary: '#111827',
    primaryHover: '#030712',
    accent: '#b45309',
    bg: '#f5f5f4',
    surface: '#ffffff',
    border: '#e7e5e4',
    text: '#171717',
    body: '#44403c',
    muted: '#78716c',
  },
  'Midnight Mint': {
    primary: '#10b981',
    primaryHover: '#059669',
    accent: '#38bdf8',
    bg: '#07131f',
    surface: '#0f2231',
    border: '#1f3a4d',
    text: '#ecfeff',
    body: '#c2dbe6',
    muted: '#88a8bb',
  },
  'Cyber Noir': {
    primary: '#6366f1',
    primaryHover: '#4f46e5',
    accent: '#22d3ee',
    bg: '#030712',
    surface: '#101828',
    border: '#243244',
    text: '#f8fafc',
    body: '#c9d7e3',
    muted: '#7b8da2',
  },
};

export const MOCK_CATEGORIES: MenuCategory[] = [
  { id: 'signature', name: 'Signature', icon: '⭐' },
  { id: 'sandwiches', name: 'Handhelds', icon: '🥪' },
  { id: 'bowls', name: 'Bowls', icon: '🥗' },
  { id: 'drinks', name: 'Drinks', icon: '🥤' },
  { id: 'desserts', name: 'Desserts', icon: '🍪' },
];

const createItem = (item: MenuItem): MenuItem => item;

const createCartItems = (menu: MenuItem[], itemIds: string[]): CartItem[] => {
  return itemIds
    .map((itemId, index) => {
      const item = menu.find((entry) => entry.id === itemId);
      if (!item) {
        return null;
      }

      return {
        id: `${item.id}-${index}`,
        menuItemId: item.id,
        name: item.name,
        basePrice: item.price,
        quantity: 1,
        selectedModifiers: [],
      };
    })
    .filter((item): item is CartItem => Boolean(item));
};

const createOrder = ({
  id,
  orderNumber,
  status,
  type,
  itemIds,
  menu,
  subtotal,
  discount = 0,
  discountLabel,
  tax,
  deliveryFee = 0,
  tip,
  total,
  customerName,
  paymentMethod,
  paymentStatus = 'paid',
  minutesAgo,
  estimatedTime,
  customerEmail,
  customerPhone,
  address,
  notes,
  splitPayment,
  tenderedCash,
  changeDue,
  staffId,
  staffName,
}: {
  id: string;
  orderNumber: string;
  status: Order['status'];
  type: Order['type'];
  itemIds: string[];
  menu: MenuItem[];
  subtotal: number;
  discount?: number;
  discountLabel?: string;
  tax: number;
  deliveryFee?: number;
  tip: number;
  total: number;
  customerName: string;
  paymentMethod: Order['paymentMethod'];
  paymentStatus?: Order['paymentStatus'];
  minutesAgo: number;
  estimatedTime: string;
  customerEmail?: string;
  customerPhone?: string;
  address?: string;
  notes?: string;
  splitPayment?: boolean;
  tenderedCash?: number;
  changeDue?: number;
  staffId?: string;
  staffName?: string;
}): Order => ({
  id,
  orderNumber,
  status,
  type,
  items: createCartItems(menu, itemIds),
  subtotal,
  discount,
  discountLabel,
  tax,
  deliveryFee,
  tip,
  total,
  customerName,
  customerEmail,
  customerPhone,
  address,
  paymentMethod,
  paymentStatus,
  createdAt: new Date(Date.now() - minutesAgo * 60 * 1000).toISOString(),
  estimatedTime,
  notes,
  splitPayment,
  tenderedCash,
  changeDue,
  staffId,
  staffName,
});

const clonePreset = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

const northstarTenant: TenantConfig = {
  id: 'northstar-counter',
  name: 'Northstar Counter Co.',
  logo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=500&q=80',
  coverImage: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1600&q=80',
  theme: 'Retail Aurora',
  currency: '$',
  taxRate: 0.0825,
  deliveryFee: 3.5,
  minOrder: 10,
  address: '184 Mercer Ave, Brooklyn, NY',
  phone: '+1 (555) 240-0198',
  email: 'hello@northstarcounter.com',
  hours: 'Mon-Sun 7:00 AM - 9:00 PM',
  story: 'Bright all-day counter cafe with toasted sandwiches, market bowls, and premium bottled drinks.',
  defaultTipOptions: [0, 10, 15, 20],
};

const northstarMenu: MenuItem[] = [
  createItem({
    id: 'item1',
    categoryId: 'signature',
    sku: 'NS-101',
    name: 'Hot Honey Chicken Melt',
    description: 'Grilled chicken, provolone, pickled onions, hot honey drizzle, toasted potato roll.',
    price: 14.5,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 8,
    inventoryCount: 18,
    lowStockThreshold: 6,
    modifierGroups: [
      {
        id: 'bread',
        name: 'Bread',
        minSelection: 1,
        maxSelection: 1,
        options: [
          { id: 'bread-roll', name: 'Potato Roll', price: 0 },
          { id: 'bread-ciabatta', name: 'Ciabatta', price: 1 },
          { id: 'bread-wrap', name: 'Wrap', price: 0.5 },
        ],
      },
      {
        id: 'extras',
        name: 'Extras',
        minSelection: 0,
        maxSelection: 3,
        options: [
          { id: 'extra-avocado', name: 'Avocado', price: 2 },
          { id: 'extra-bacon', name: 'Bacon', price: 2.5 },
          { id: 'extra-cheese', name: 'Extra Cheese', price: 1.5 },
        ],
      },
    ],
  }),
  createItem({
    id: 'item2',
    categoryId: 'signature',
    sku: 'NS-102',
    name: 'Street Cart Rice Bowl',
    description: 'Charred chicken, turmeric rice, cucumber salad, tahini green sauce.',
    price: 15.75,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 14,
    lowStockThreshold: 5,
    modifierGroups: [
      {
        id: 'protein',
        name: 'Protein',
        minSelection: 1,
        maxSelection: 1,
        options: [
          { id: 'protein-chicken', name: 'Chicken', price: 0 },
          { id: 'protein-falafel', name: 'Falafel', price: 0 },
          { id: 'protein-steak', name: 'Steak', price: 3.5 },
        ],
      },
    ],
  }),
  createItem({
    id: 'item3',
    categoryId: 'sandwiches',
    sku: 'NS-201',
    name: 'Citrus Turkey Club',
    description: 'Roasted turkey, lemon aioli, tomato jam, arugula, multigrain toast.',
    price: 13.25,
    image: 'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 6,
    inventoryCount: 22,
    lowStockThreshold: 7,
  }),
  createItem({
    id: 'item4',
    categoryId: 'sandwiches',
    sku: 'NS-202',
    name: 'Pressed Veggie Panini',
    description: 'Mozzarella, pesto, zucchini ribbons, roasted peppers, balsamic glaze.',
    price: 12.75,
    image: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 6,
    inventoryCount: 11,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item5',
    categoryId: 'bowls',
    sku: 'NS-301',
    name: 'Market Harvest Salad',
    description: 'Baby kale, quinoa, roasted carrots, goat cheese, maple Dijon vinaigrette.',
    price: 13.95,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 5,
    inventoryCount: 9,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item6',
    categoryId: 'bowls',
    sku: 'NS-302',
    name: 'Miso Noodle Bowl',
    description: 'Sesame noodles, soft egg, bok choy, mushrooms, chili crunch.',
    price: 14.25,
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 4,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item7',
    categoryId: 'drinks',
    sku: 'NS-401',
    name: 'Sparkling Citrus Tonic',
    description: 'Fresh orange, rosemary syrup, sparkling water, crushed ice.',
    price: 4.95,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 2,
    inventoryCount: 30,
    lowStockThreshold: 8,
  }),
  createItem({
    id: 'item8',
    categoryId: 'drinks',
    sku: 'NS-402',
    name: 'Cold Brew Float',
    description: 'Small batch cold brew with vanilla soft serve.',
    price: 6.5,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80',
    available: false,
    prepTimeMinutes: 3,
    inventoryCount: 0,
    lowStockThreshold: 5,
  }),
  createItem({
    id: 'item9',
    categoryId: 'desserts',
    sku: 'NS-501',
    name: 'Brown Butter Cookie',
    description: 'Warm sea salt cookie with dark chocolate shards.',
    price: 3.95,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 1,
    inventoryCount: 20,
    lowStockThreshold: 6,
  }),
  createItem({
    id: 'item10',
    categoryId: 'desserts',
    sku: 'NS-502',
    name: 'Lemon Olive Oil Cake',
    description: 'Bright citrus crumb with whipped mascarpone.',
    price: 6.25,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 1,
    inventoryCount: 8,
    lowStockThreshold: 4,
  }),
];

const northstarOrders: Order[] = [
  createOrder({
    id: 'order1',
    orderNumber: '1047',
    status: 'received',
    type: 'takeout',
    itemIds: ['item1', 'item7'],
    menu: northstarMenu,
    subtotal: 19.45,
    tax: 1.6,
    tip: 2.92,
    total: 23.97,
    customerName: 'Walk-in Guest',
    paymentMethod: 'card',
    minutesAgo: 8,
    estimatedTime: '8 mins',
    customerEmail: 'guest1047@example.com',
    staffId: 'staff2',
    staffName: 'Andre Lewis',
  }),
  createOrder({
    id: 'order2',
    orderNumber: '1046',
    status: 'preparing',
    type: 'delivery',
    itemIds: ['item2', 'item9'],
    menu: northstarMenu,
    subtotal: 19.7,
    discount: 2,
    discountLabel: 'Promo',
    tax: 1.46,
    deliveryFee: 3.5,
    tip: 3.75,
    total: 26.41,
    customerName: 'Jamie Rivers',
    paymentMethod: 'gift-card',
    minutesAgo: 18,
    estimatedTime: '12 mins',
    customerPhone: '(555) 812-2210',
    address: '46 Atlantic Ave, Brooklyn, NY',
    notes: 'Leave at pickup shelf if courier is early.',
    splitPayment: true,
    staffId: 'staff1',
    staffName: 'Maya Chen',
  }),
  createOrder({
    id: 'order3',
    orderNumber: '1045',
    status: 'ready',
    type: 'dine-in',
    itemIds: ['item3', 'item5', 'item10'],
    menu: northstarMenu,
    subtotal: 33.45,
    tax: 2.76,
    tip: 6.69,
    total: 42.9,
    customerName: 'Table 8',
    paymentMethod: 'cash',
    minutesAgo: 31,
    estimatedTime: 'Ready now',
    tenderedCash: 50,
    changeDue: 7.1,
    staffId: 'staff2',
    staffName: 'Andre Lewis',
  }),
];

const cedarTenant: TenantConfig = {
  id: 'cedar-flame',
  name: 'Cedar Flame Tacos',
  logo: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=500&q=80',
  coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1600&q=80',
  theme: 'Cafe Cream',
  currency: '$',
  taxRate: 0.0875,
  deliveryFee: 4,
  minOrder: 12,
  address: '71 River Street, Austin, TX',
  phone: '+1 (555) 800-2144',
  email: 'hola@cedarflame.com',
  hours: 'Tue-Sun 11:00 AM - 10:00 PM',
  story: 'Neighborhood taco counter with mesquite-grilled meats, agua frescas, and warm late-night service.',
  defaultTipOptions: [0, 12, 18, 22],
};

const cedarMenu: MenuItem[] = [
  createItem({
    id: 'item1',
    categoryId: 'signature',
    sku: 'CF-101',
    name: 'Cedar Flame Taco Trio',
    description: 'Three mesquite-grilled tacos with salsa roja, onion relish, and charred lime.',
    price: 15.5,
    image: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 24,
    lowStockThreshold: 8,
    modifierGroups: [
      {
        id: 'protein',
        name: 'Protein',
        minSelection: 1,
        maxSelection: 1,
        options: [
          { id: 'carne-asada', name: 'Carne Asada', price: 0 },
          { id: 'pollo-adobo', name: 'Pollo Adobo', price: 0 },
          { id: 'mushroom-carnitas', name: 'Mushroom Carnitas', price: 1 },
        ],
      },
    ],
  }),
  createItem({
    id: 'item2',
    categoryId: 'signature',
    sku: 'CF-102',
    name: 'Fire Roasted Burrito Bowl',
    description: 'Cilantro rice, black beans, pico, queso fresco, and roasted chile crema.',
    price: 14.95,
    image: 'https://images.unsplash.com/photo-1539136788836-5699e78bfc75?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 6,
    inventoryCount: 16,
    lowStockThreshold: 5,
  }),
  createItem({
    id: 'item3',
    categoryId: 'sandwiches',
    sku: 'CF-201',
    name: 'Birria Quesadilla',
    description: 'Crisped flour tortilla with melty cheese, braised beef, consommé dip.',
    price: 13.75,
    image: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 8,
    inventoryCount: 14,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item4',
    categoryId: 'sandwiches',
    sku: 'CF-202',
    name: 'Griddled Street Cemita',
    description: 'Sesame bun, chipotle chicken, avocado, Oaxaca cheese, herb slaw.',
    price: 12.95,
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 10,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item5',
    categoryId: 'bowls',
    sku: 'CF-301',
    name: 'Citrus Chopped Salad',
    description: 'Romaine, pepitas, mango, queso fresco, jalapeno ranch.',
    price: 11.95,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 4,
    inventoryCount: 13,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item6',
    categoryId: 'bowls',
    sku: 'CF-302',
    name: 'Pozole Verde Cup',
    description: 'Slow-simmered hominy soup with salsa verde chicken and crispy cabbage.',
    price: 9.95,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 5,
    inventoryCount: 6,
    lowStockThreshold: 3,
  }),
  createItem({
    id: 'item7',
    categoryId: 'drinks',
    sku: 'CF-401',
    name: 'Watermelon Agua Fresca',
    description: 'Fresh melon juice, lime, mint, and sparkling topper.',
    price: 4.5,
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 1,
    inventoryCount: 28,
    lowStockThreshold: 8,
  }),
  createItem({
    id: 'item8',
    categoryId: 'drinks',
    sku: 'CF-402',
    name: 'Mexican Mocha Cold Brew',
    description: 'Cold brew, chocolate, cinnamon whip, and smoked sugar.',
    price: 6.25,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 2,
    inventoryCount: 12,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item9',
    categoryId: 'desserts',
    sku: 'CF-501',
    name: 'Churro Bites',
    description: 'Warm cinnamon churros with dulce de leche dip.',
    price: 5.95,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 3,
    inventoryCount: 18,
    lowStockThreshold: 5,
  }),
  createItem({
    id: 'item10',
    categoryId: 'desserts',
    sku: 'CF-502',
    name: 'Tres Leches Jar',
    description: 'Vanilla sponge, sweet cream soak, toasted coconut topping.',
    price: 6.75,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 1,
    inventoryCount: 9,
    lowStockThreshold: 4,
  }),
];

const cedarOrders: Order[] = [
  createOrder({
    id: 'order1',
    orderNumber: '2214',
    status: 'received',
    type: 'takeout',
    itemIds: ['item1', 'item7'],
    menu: cedarMenu,
    subtotal: 20,
    tax: 1.75,
    tip: 3,
    total: 24.75,
    customerName: 'Window Pickup',
    paymentMethod: 'card',
    minutesAgo: 6,
    estimatedTime: '7 mins',
    staffId: 'staff2',
    staffName: 'Andre Lewis',
  }),
  createOrder({
    id: 'order2',
    orderNumber: '2213',
    status: 'preparing',
    type: 'delivery',
    itemIds: ['item2', 'item9'],
    menu: cedarMenu,
    subtotal: 20.9,
    tax: 1.83,
    deliveryFee: 4,
    tip: 4.18,
    total: 30.91,
    customerName: 'Chris Dalton',
    paymentMethod: 'manual-entry',
    minutesAgo: 17,
    estimatedTime: '15 mins',
    address: '12 Trinity St, Austin, TX',
    staffId: 'staff1',
    staffName: 'Maya Chen',
  }),
];

const harborTenant: TenantConfig = {
  id: 'harbor-bento',
  name: 'Harbor Bento Bar',
  logo: 'https://images.unsplash.com/photo-1515669097368-22e68427d265?auto=format&fit=crop&w=500&q=80',
  coverImage: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1600&q=80',
  theme: 'Midnight Mint',
  currency: '$',
  taxRate: 0.08,
  deliveryFee: 4.25,
  minOrder: 14,
  address: '310 Harborview Blvd, Seattle, WA',
  phone: '+1 (555) 908-7711',
  email: 'team@harborbento.com',
  hours: 'Mon-Sat 11:30 AM - 9:30 PM',
  story: 'Modern bento counter with polished sushi sets, rice bowls, sparkling teas, and fast lunch service.',
  defaultTipOptions: [0, 12, 18, 20],
};

const harborMenu: MenuItem[] = [
  createItem({
    id: 'item1',
    categoryId: 'signature',
    sku: 'HB-101',
    name: 'Harbor Bento Set',
    description: 'Salmon teriyaki, sesame rice, pickled cucumber, and chilled soba salad.',
    price: 18.5,
    image: 'https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 20,
    lowStockThreshold: 6,
  }),
  createItem({
    id: 'item2',
    categoryId: 'signature',
    sku: 'HB-102',
    name: 'Spicy Tuna Rice Box',
    description: 'Tuna, avocado, crisp shallots, spicy mayo, and furikake rice.',
    price: 17.95,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 6,
    inventoryCount: 15,
    lowStockThreshold: 5,
  }),
  createItem({
    id: 'item3',
    categoryId: 'sandwiches',
    sku: 'HB-201',
    name: 'Katsu Milk Bread Sando',
    description: 'Crispy chicken cutlet, cabbage slaw, yuzu aioli, fluffy milk bread.',
    price: 14.95,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 13,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item4',
    categoryId: 'sandwiches',
    sku: 'HB-202',
    name: 'Tempura Shrimp Hand Roll Pair',
    description: 'Two crisp nori hand rolls with tempura shrimp and mango slaw.',
    price: 13.5,
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 5,
    inventoryCount: 12,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item5',
    categoryId: 'bowls',
    sku: 'HB-301',
    name: 'Miso Greens Bowl',
    description: 'Baby greens, edamame, sesame seeds, miso vinaigrette, and warm rice.',
    price: 13.75,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 4,
    inventoryCount: 10,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item6',
    categoryId: 'bowls',
    sku: 'HB-302',
    name: 'Udon Comfort Bowl',
    description: 'Brothy udon, mushrooms, spinach, soft egg, and scallion oil.',
    price: 15.25,
    image: 'https://images.unsplash.com/photo-1617622141675-d3005b9067c5?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 7,
    inventoryCount: 7,
    lowStockThreshold: 3,
  }),
  createItem({
    id: 'item7',
    categoryId: 'drinks',
    sku: 'HB-401',
    name: 'Yuzu Sparkling Tea',
    description: 'Citrus tea, jasmine bubbles, and shaved ice.',
    price: 5.25,
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 2,
    inventoryCount: 26,
    lowStockThreshold: 8,
  }),
  createItem({
    id: 'item8',
    categoryId: 'drinks',
    sku: 'HB-402',
    name: 'Matcha Cream Cooler',
    description: 'Ceremonial matcha, vanilla cloud, and cold milk.',
    price: 6.95,
    image: 'https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 2,
    inventoryCount: 14,
    lowStockThreshold: 4,
  }),
  createItem({
    id: 'item9',
    categoryId: 'desserts',
    sku: 'HB-501',
    name: 'Mochi Trio',
    description: 'Seasonal mochi assortment with toasted sesame dust.',
    price: 5.5,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 1,
    inventoryCount: 18,
    lowStockThreshold: 5,
  }),
  createItem({
    id: 'item10',
    categoryId: 'desserts',
    sku: 'HB-502',
    name: 'Black Sesame Cheesecake Cup',
    description: 'Creamy cheesecake set in a grab-and-go cup with sesame crumble.',
    price: 6.95,
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=900&q=80',
    available: true,
    prepTimeMinutes: 1,
    inventoryCount: 8,
    lowStockThreshold: 4,
  }),
];

const harborOrders: Order[] = [
  createOrder({
    id: 'order1',
    orderNumber: '3312',
    status: 'received',
    type: 'takeout',
    itemIds: ['item1', 'item7'],
    menu: harborMenu,
    subtotal: 23.75,
    tax: 1.9,
    tip: 3.56,
    total: 29.21,
    customerName: 'Harbor Walk-In',
    paymentMethod: 'card',
    minutesAgo: 5,
    estimatedTime: '9 mins',
    staffId: 'staff2',
    staffName: 'Andre Lewis',
  }),
  createOrder({
    id: 'order2',
    orderNumber: '3311',
    status: 'ready',
    type: 'delivery',
    itemIds: ['item2', 'item9'],
    menu: harborMenu,
    subtotal: 23.45,
    tax: 1.88,
    deliveryFee: 4.25,
    tip: 4.69,
    total: 34.27,
    customerName: 'Avery Olsen',
    paymentMethod: 'gift-card',
    minutesAgo: 20,
    estimatedTime: 'Ready now',
    address: '809 First Ave, Seattle, WA',
    staffId: 'staff1',
    staffName: 'Maya Chen',
  }),
];

export const BUSINESS_PRESETS: BusinessPreset[] = [
  {
    id: northstarTenant.id,
    name: northstarTenant.name,
    description: 'Bright cafe counter demo with sandwiches and bowls.',
    tenantConfig: northstarTenant,
    menu: northstarMenu,
    orders: northstarOrders,
  },
  {
    id: cedarTenant.id,
    name: cedarTenant.name,
    description: 'Warm taco counter concept with bold photos and late-night energy.',
    tenantConfig: cedarTenant,
    menu: cedarMenu,
    orders: cedarOrders,
  },
  {
    id: harborTenant.id,
    name: harborTenant.name,
    description: 'Modern bento and tea concept with sleek, premium visuals.',
    tenantConfig: harborTenant,
    menu: harborMenu,
    orders: harborOrders,
  },
];

export const DEFAULT_PRESET_ID = BUSINESS_PRESETS[0].id;
export const DEFAULT_TENANT_CONFIG = clonePreset(BUSINESS_PRESETS[0].tenantConfig);
export const MOCK_MENU = clonePreset(BUSINESS_PRESETS[0].menu);
export const MOCK_ORDERS = clonePreset(BUSINESS_PRESETS[0].orders);

export const getBusinessPreset = (presetId: string): BusinessPreset => {
  return clonePreset(BUSINESS_PRESETS.find((preset) => preset.id === presetId) || BUSINESS_PRESETS[0]);
};

export const MOCK_STAFF: StaffMember[] = [
  { id: 'staff1', name: 'Maya Chen', role: 'manager', pin: '2481', shiftLabel: 'Opening Lead', status: 'clocked-in' },
  { id: 'staff2', name: 'Andre Lewis', role: 'cashier', pin: '4182', shiftLabel: 'Counter / Expo', status: 'clocked-in' },
  { id: 'staff3', name: 'Sofia Ramirez', role: 'kitchen', pin: '7721', shiftLabel: 'Hot Line', status: 'clocked-in' },
  { id: 'staff4', name: 'Noah Patel', role: 'owner', pin: '9911', shiftLabel: 'On Call', status: 'break' },
];
